---
- hosts: all
  become: true
  # gather_facts: false
  # vars:
  #   - myvar: value
  vars_files:
    - vars/enc_vars.yml
    - vars/vars.yml
  tasks:
  #   - name: Install Python
  #     include_role:
  #       name: "{{ rolevar.name }}"
  #     vars: "{{ rolevar.vars | default(omit) }}"
  #     with_items:
  #       - name: coaxial.base
  #       - name: coaxial.raw-python
  #         vars:
  #           rawpython__os_family: Debian
  #     loop_control:
  #       loop_var: rolevar
